FROM node:17.3.1

WORKDIR /app

COPY yarn.lock ./
COPY package.json ./
COPY server/package.json ./server/
COPY web/package.json ./web/

RUN yarn

COPY . .

ENV NODE_ENV=production

RUN yarn build

CMD ["./start.sh"]
