branch-defaults:
  main:
    environment: hello-fastify-rtk-dev
    group_suffix: null
global:
  application_name: hello-fastify-rtk
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
